import { db } from '../db/index.ts';
import { suppliers, products, productAttributes, crawlLogs } from '../db/schema.ts';
import { getDatabaseStats } from '../db/queries.ts';

/**
 * 5 Defined Target OEM Fitness Equipment Manufacturers from Made-in-China
 * Organizados estritamente na árvore: Fábrica -> Linhas de Produtos (Product Groups) -> SKUs / Modelos
 */
export const TARGET_MIC_SUPPLIERS = [
  {
    supplierId: 'sup_brtw_baodelong',
    supplierName: 'SHANDONG BAODELONG (BRTW) FITNESS CO., LTD.',
    homepageUrl: 'https://brtw-fitness.en.made-in-china.com/?pv_id=1k3a3l3gm749&faw_id=1k3a3l8rv6f0&bv_id=1k3a3l8s0aba&pbv_id=1k3a3l26c032',
    cleanUrl: 'https://brtw-fitness.en.made-in-china.com/',
    businessType: 'Fabricante OEM / ODM Especializado em Biomecânica Pesada',
    foundedDate: '2001',
    employees: 850,
    plantAreaSqm: 260000,
    registeredCapital: '30,000,000 RMB',
    responseTimeAvg30d: '< 3h (30d avg)',
    contactName: 'Mr. Steven Zhao (Diretoria Comercial OEM)',
    contactGender: 'Mr.',
    domainUserId: 'brtw-fitness',
    paymentTerms: ['T/T (30% sinal + 70% embarque)', 'L/C at sight', 'Western Union'],
    incoterms: ['FOB Qingdao', 'CIF Santos/Paranaguá', 'CFR', 'EXW Dezhou', 'DDP'],
    nearestPorts: ['Qingdao Port (180 km)', 'Tianjin Port (220 km)'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 16,
    productionMachines: [
      'Han’s Laser 12KW High Speed Fiber Pipe Cutting',
      'Fanuc Automated Robotic Welding Cells (32 unidades)',
      'Nordson Powder Coating Automated Electrostatic Line',
      'Heavy Plate Hydraulic Press 500 Tons',
      'CNC 3D Cold Mandrel Tube Benders',
    ],
    qaInspectors: 35,
    rdEngineers: 45,
    inspectionMethod: 'Rigorosa inspeção em 4 etapas: Matéria-prima (tubo Q235 3mm), Ultrassom de Solda, Teste de Fadiga 500k ciclos e Carga de Ruptura',
    inspectionType: 'Fábrica Homologada CE, ISO9001:2015, ISO14001, OHSAS18001 e TÜV Rheinland',
    exportYears: 23,
    mainMarkets: ['América do Sul (Brasil)', 'Europa', 'América do Norte', 'Oriente Médio', 'Sudeste Asiático'],
    repeatBuyersPercent: '95.1%',
    foreignTradeStaff: 40,
    products: [
      // =========================================================================
      // LINHA 1: 2025 New HS Series (URL Fornecida pelo Usuário - Linha Prioritária)
      // URL Linha: https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html
      // =========================================================================
      {
        productId: 'brtw_hs01_vertical_chest_press',
        modelNo: 'HS01',
        title: 'Commercial Grade Vertical Chest Press for Gym Professionals (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product/CrbYNUaKYTcJ/China-Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.html?pv_id=1k3a4nv1f3f1&faw_id=1k3a4nvsc4b1&bv_id=1k3a4odr285d&pbv_id=1k3a4nufl173',
        productLine: '2025 New HS Series',
        priceMin: 980,
        priceMax: 1280,
        currency: 'USD',
        moq: 1,
        sku: 'HS01-VCP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1040,
        widthMm: 1450,
        heightMm: 1630,
        netWeightKg: 210,
        grossWeightKg: 245,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada) com Travas de Aço e Filme Bolha Protetor',
        material: 'Tubo de Aço Carbono Q235 de Alta Resistência (60x100x3.0mm)',
        specification: '1040*1450*1630mm | Bateria de Peso: 100kg | Tubo 60x100x3mm',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'RoHS', 'EN957-1/2'],
        images: [
          'https://image.made-in-china.com/371f3j00rawQvolhspkT/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
          'https://image.made-in-china.com/371f3j00YadTeJiCHrqU/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Commercial Grade Vertical Chest Press for Gym Professionals da Linha 2025 New HS Series. Trajetória convergente ergonômica com manoplas multi-pegada, estofamento em PU injetado de alta densidade revestido em couro sintético náutico, pintura eletrostática a pó com cura em forno a 200°C e cabos de aço aeronáutico lubrificados internamente com capacidade de 1.400 kgf.',
        rawAttributes: {
          'Product Name': 'Vertical Chest Press',
          'Item Number': 'HS01',
          'Model NO.': 'HS01',
          'Series': '2025 New HS Series',
          'Size': '1040*1450*1630mm',
          'Weight stack': '100kg',
          'Net Weight': '210kg',
          'Gross Weight': '245kg',
          'Steel Tube Size': '60x100x3.0mm',
          'Material': 'Top quality steel tube Q235',
          'Range of application': 'Professional gym club / Fitness center',
          'Packaging': 'Export Plywood Case',
          'Payment Term': 'T/T, L/C at sight, Western Union',
          'MOQ': '1 set',
          'Delivery Time': '7-15 days',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs02_incline_chest_press',
        modelNo: 'HS02',
        title: 'Commercial Grade Incline Chest Press Machine (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 1020,
        priceMax: 1320,
        currency: 'USD',
        moq: 1,
        sku: 'HS02-ICP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1120,
        widthMm: 1520,
        heightMm: 1650,
        netWeightKg: 220,
        grossWeightKg: 255,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada) com Travas Metálicas',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1120*1520*1650mm | Bateria de Peso: 100kg | Tubo 60x100x3mm',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'RoHS'],
        images: [
          'https://image.made-in-china.com/371f3j00mTJQNshangbl/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Supino Inclinado Articulado com trajetória biomecânica em convergência para isolamento da porção clavicular do peitoral maior. Braços de movimento independente para equilíbrio muscular.',
        rawAttributes: {
          'Product Name': 'Incline Chest Press',
          'Item Number': 'HS02',
          'Model NO.': 'HS02',
          'Series': '2025 New HS Series',
          'Size': '1120*1520*1650mm',
          'Weight stack': '100kg',
          'Net Weight': '220kg',
          'Gross Weight': '255kg',
          'Steel Tube': 'Q235 60x100x3mm',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs03_wide_chest_press',
        modelNo: 'HS03',
        title: 'Commercial Grade Wide Chest Press Decline (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 990,
        priceMax: 1290,
        currency: 'USD',
        moq: 1,
        sku: 'HS03-WCP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1180,
        widthMm: 1600,
        heightMm: 1680,
        netWeightKg: 215,
        grossWeightKg: 250,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1180*1600*1680mm | Bateria de Peso: 100kg | Tubo 60x100x3mm',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00SadEJuIMfrky/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Supino Declinado / Wide Press para ênfase no feixe inferior do peitoral maior. Empunhaduras duplas de pegada neutra e pronada emborrachadas com ponteiras em alumínio usinado.',
        rawAttributes: {
          'Product Name': 'Wide Chest Press Decline',
          'Item Number': 'HS03',
          'Model NO.': 'HS03',
          'Series': '2025 New HS Series',
          'Size': '1180*1600*1680mm',
          'Weight stack': '100kg',
          'Net Weight': '215kg',
          'Gross Weight': '250kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs04_shoulder_press',
        modelNo: 'HS04',
        title: 'Commercial Grade Shoulder Press Converging (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 970,
        priceMax: 1260,
        currency: 'USD',
        moq: 1,
        sku: 'HS04-SHP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1250,
        widthMm: 1420,
        heightMm: 1580,
        netWeightKg: 205,
        grossWeightKg: 240,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1250*1420*1580mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00OTdEuUqhsgcY/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Desenvolvimento de Ombros com curva de resistência biomecânica constante e pegadas ergonômicas para proteção da articulação gleno-umeral.',
        rawAttributes: {
          'Product Name': 'Shoulder Press',
          'Item Number': 'HS04',
          'Model NO.': 'HS04',
          'Series': '2025 New HS Series',
          'Size': '1250*1420*1580mm',
          'Net Weight': '205kg',
          'Gross Weight': '240kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs05_lat_pulldown',
        modelNo: 'HS05',
        title: 'Commercial Grade Diverging Lat Pulldown High Pull (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 1050,
        priceMax: 1350,
        currency: 'USD',
        moq: 1,
        sku: 'HS05-LPD',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1480,
        widthMm: 1350,
        heightMm: 1950,
        netWeightKg: 225,
        grossWeightKg: 260,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1480*1350*1950mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00ZamTuJkKZgqf/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Puxada Alta Divergente para ativação máxima do grande dorsal sem sobrecarga nos punhos e cotovelos. Rolos ajustáveis para fixação das coxas com acionamento rápido por pino magnético.',
        rawAttributes: {
          'Product Name': 'Diverging Lat Pulldown',
          'Item Number': 'HS05',
          'Model NO.': 'HS05',
          'Series': '2025 New HS Series',
          'Size': '1480*1350*1950mm',
          'Net Weight': '225kg',
          'Gross Weight': '260kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs06_seated_row',
        modelNo: 'HS06',
        title: 'Commercial Grade Seated Low Row Machine (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 980,
        priceMax: 1280,
        currency: 'USD',
        moq: 1,
        sku: 'HS06-SRW',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1320,
        widthMm: 1280,
        heightMm: 1620,
        netWeightKg: 210,
        grossWeightKg: 245,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1320*1280*1620mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00KtdTiglPHpcZ/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Remada Sentada Articulada com apoio torácico ajustável de múltiplos estágios para suporte da coluna e foco na retração escapular e miolo das costas.',
        rawAttributes: {
          'Product Name': 'Seated Low Row',
          'Item Number': 'HS06',
          'Model NO.': 'HS06',
          'Series': '2025 New HS Series',
          'Size': '1320*1280*1620mm',
          'Net Weight': '210kg',
          'Gross Weight': '245kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs07_biceps_curl',
        modelNo: 'HS07',
        title: 'Commercial Grade Arm Preacher Biceps Curl (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 890,
        priceMax: 1150,
        currency: 'USD',
        moq: 1,
        sku: 'HS07-BCL',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1050,
        widthMm: 1120,
        heightMm: 1400,
        netWeightKg: 165,
        grossWeightKg: 195,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1050*1120*1400mm | Bateria de Peso: 80kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00DEwTgViqYzoZ/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Rosca Scott / Bíceps Articulada com manoplas giratórias e cam excêntrico que garante torque uniforme ao longo de toda a contração do pico do bíceps.',
        rawAttributes: {
          'Product Name': 'Preacher Biceps Curl',
          'Item Number': 'HS07',
          'Model NO.': 'HS07',
          'Series': '2025 New HS Series',
          'Size': '1050*1120*1400mm',
          'Net Weight': '165kg',
          'Gross Weight': '195kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs08_triceps_dip',
        modelNo: 'HS08',
        title: 'Commercial Grade Seated Triceps Dip Extension (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 910,
        priceMax: 1180,
        currency: 'USD',
        moq: 1,
        sku: 'HS08-TDP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1200,
        widthMm: 1150,
        heightMm: 1500,
        netWeightKg: 175,
        grossWeightKg: 205,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1200*1150*1500mm | Bateria de Peso: 80kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00FaJtuIqGvrbR/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Tríceps Dip Sentado com cinto de contenção abdominal e manoplas de dupla abertura para usuários de todas as estaturas.',
        rawAttributes: {
          'Product Name': 'Seated Triceps Dip',
          'Item Number': 'HS08',
          'Model NO.': 'HS08',
          'Series': '2025 New HS Series',
          'Size': '1200*1150*1500mm',
          'Net Weight': '175kg',
          'Gross Weight': '205kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs09_leg_extension',
        modelNo: 'HS09',
        title: 'Commercial Grade Leg Extension Quadriceps (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 1060,
        priceMax: 1360,
        currency: 'USD',
        moq: 1,
        sku: 'HS09-LEX',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1280,
        widthMm: 1180,
        heightMm: 1520,
        netWeightKg: 230,
        grossWeightKg: 265,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1280*1180*1520mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://image.made-in-china.com/371f3j00KawQlhVoZubj/Commercial-Grade-Vertical-Chest-Press-for-Gym-Professionals.webp',
        ],
        description: 'Cadeira Extensora de alta precisão com rolete de apoio auto-alinhável à tíbia e encosto ajustável com mola a gás para alinhamento instantâneo do eixo do joelho.',
        rawAttributes: {
          'Product Name': 'Leg Extension',
          'Item Number': 'HS09',
          'Model NO.': 'HS09',
          'Series': '2025 New HS Series',
          'Size': '1280*1180*1520mm',
          'Net Weight': '230kg',
          'Gross Weight': '265kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs10_leg_curl',
        modelNo: 'HS10',
        title: 'Commercial Grade Prone Seated Leg Curl (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 1080,
        priceMax: 1380,
        currency: 'USD',
        moq: 1,
        sku: 'HS10-LCL',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1450,
        widthMm: 1120,
        heightMm: 1520,
        netWeightKg: 235,
        grossWeightKg: 270,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1450*1120*1520mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Mesa Flexora / Cadeira Flexora para isolamento dos isquiotibiais com ângulo anatômico para descompressão da lombar durante o esforço máximo.',
        rawAttributes: {
          'Product Name': 'Seated Leg Curl',
          'Item Number': 'HS10',
          'Model NO.': 'HS10',
          'Series': '2025 New HS Series',
          'Size': '1450*1120*1520mm',
          'Net Weight': '235kg',
          'Gross Weight': '270kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs11_leg_press_linear',
        modelNo: 'HS11',
        title: 'Commercial Grade 45 Degree Linear Leg Press (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 1450,
        priceMax: 1850,
        currency: 'USD',
        moq: 1,
        sku: 'HS11-LGP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 2150,
        widthMm: 1620,
        heightMm: 1480,
        netWeightKg: 310,
        grossWeightKg: 360,
        packagingType: 'Caixa de Madeira Plywood Exportação Reforçada para Alta Carga',
        material: 'Tubo de Aço Carbono Estrutural Q235B (80x120x3.5mm)',
        specification: '2150*1620*1480mm | Carga Máxima Suportada: 650kg | Guias Lineares Retificadas 40mm',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '2,500 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Leg Press 45 Graus Linear de Alta Resistência para Academias Comerciais. Guias maciças retificadas e polidas com rolamentos lineares selados para deslizamento ultra silencioso, plataforma de pés ampla antiderrapante em alumínio com ajuste de inclinação.',
        rawAttributes: {
          'Product Name': '45 Degree Linear Leg Press',
          'Item Number': 'HS11',
          'Model NO.': 'HS11',
          'Series': '2025 New HS Series',
          'Size': '2150*1620*1480mm',
          'Net Weight': '310kg',
          'Gross Weight': '360kg',
          'Packaging': 'Export Heavy-Duty Plywood Case',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'brtw_hs12_standing_calf_raise',
        modelNo: 'HS12',
        title: 'Commercial Grade Seated Standing Calf Raise (2025 New HS Series)',
        url: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
        productLine: '2025 New HS Series',
        priceMin: 890,
        priceMax: 1190,
        currency: 'USD',
        moq: 1,
        sku: 'HS12-CLF',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1100,
        widthMm: 1050,
        heightMm: 1720,
        netWeightKg: 185,
        grossWeightKg: 215,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada)',
        material: 'Tubo de Aço Carbono Q235 (60x100x3.0mm)',
        specification: '1100*1050*1720mm | Bateria de Peso: 100kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Panturrilha Vertical com almofadas de ombro anatômicas e barra de apoio curvada que permite amplitude máxima de dorsiflexão e flexão plantar.',
        rawAttributes: {
          'Product Name': 'Standing Calf Raise',
          'Item Number': 'HS12',
          'Model NO.': 'HS12',
          'Series': '2025 New HS Series',
          'Size': '1100*1050*1720mm',
          'Net Weight': '185kg',
          'Gross Weight': '215kg',
          'Packaging': 'Export Plywood Case',
          'HS Code': '95069119',
        },
      },
      // =========================================================================
      // LINHA 2: Série BTW Pin Loaded
      // =========================================================================
      {
        productId: 'brtw_biceps_curl_6800',
        modelNo: 'BTW-6800',
        title: 'Commercial Fitness Equipment Biceps Curl Machine Pin Loaded BTW-6800',
        url: 'https://brtw-fitness.en.made-in-china.com/product/zRpUrWOYHqcM/China-Fitness-Equipment-Biceps-Curl-for-Home-Gym-Strength-Building-with-CE-Factory-Direct.html',
        productLine: 'Série BTW Pin Loaded',
        priceMin: 890,
        priceMax: 1150,
        currency: 'USD',
        moq: 1,
        sku: 'BTW-6800-BC',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1200,
        widthMm: 1150,
        heightMm: 1550,
        netWeightKg: 195,
        grossWeightKg: 230,
        packagingType: 'Engradado de Madeira Plywood para Exportação',
        material: 'Aço Estrutural Carbono Alta Tensão (Q235B 60*120*3.0mm)',
        specification: '1200*1150*1550 (mm) / Peso Líquido: 195kg',
        trademark: 'BRTW / Baodelong OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Baodelong BTW-6800 Rosca Bíceps Comercial com manoplas rotativas para alinhamento do punho e ativação do pico do bíceps.',
        rawAttributes: {
          'Model NO.': 'BTW-6800',
          'Series': 'Série BTW Pin Loaded',
          'Material': 'Steel Q235B',
          'Specification': '1200*1150*1550 (mm)',
          'HS Code': '95069119',
        },
      },
      // =========================================================================
      // LINHA 3: Série BTW Plate Loaded
      // =========================================================================
      {
        productId: 'brtw_incline_pec_fly_5000',
        modelNo: 'BTW-5000',
        title: 'Plate Loaded Incline Pec Fly Chest Exercise Machine BTW-5000',
        url: 'https://brtw-fitness.en.made-in-china.com/product/jraYnRDKHShM/China-Bodybuilding-Strength-Equipment-Commercial-Gym-Fitness-Equipment-Plate-Loaded-Machine-Incline-Pec-Fly-Chest-Exercise.html',
        productLine: 'Série BTW Plate Loaded',
        priceMin: 780,
        priceMax: 990,
        currency: 'USD',
        moq: 1,
        sku: 'BTW-5000-FLY',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1480,
        widthMm: 1280,
        heightMm: 1720,
        netWeightKg: 165,
        grossWeightKg: 195,
        packagingType: 'Caixa de Madeira Plywood com Suporte para Empilhamento',
        material: 'Tubo Oval Plano de Alta Resistência 3.0mm',
        specification: '1480*1280*1720 (mm) / Peso: 165kg',
        trademark: 'BRTW Fitness',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,500 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Crucifixo Inclinado Plate Loaded BRTW com eixos divergentes independentes.',
        rawAttributes: {
          'Model NO.': 'BTW-5000',
          'Series': 'Série BTW Plate Loaded',
          'Material': 'Steel',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // 2. MBH Fitness
  {
    supplierId: 'sup_mbh_fitness',
    supplierName: 'SHANDONG MBH FITNESS CO., LTD.',
    homepageUrl: 'https://mbhfitness.en.made-in-china.com/?pv_id=1k3a3c93gf80&faw_id=1k3a3ca2ada5&bv_id=1k3a3cjpnd09&pbv_id=1k39v9c9u00b',
    cleanUrl: 'https://mbhfitness.en.made-in-china.com/',
    businessType: 'Fabricante e Exportador OEM / ODM',
    foundedDate: '2001',
    employees: 1200,
    plantAreaSqm: 380000,
    registeredCapital: '50,000,000 RMB',
    responseTimeAvg30d: '< 2h (30d avg)',
    contactName: 'Mr. Liu Peng (Depto. Exportação OEM)',
    contactGender: 'Mr.',
    domainUserId: 'mbhfitness',
    paymentTerms: ['T/T', 'L/C at sight', 'Western Union', 'D/P'],
    incoterms: ['FOB Qingdao', 'CIF', 'CFR', 'EXW', 'DDP'],
    nearestPorts: ['Qingdao Port', 'Tianjin Port'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 24,
    productionMachines: [
      'Trumpf 15KW Laser Cutting Machine',
      'Panasonic Robotic Welding Stations (50+ units)',
      'German Wagner Automatic Electrostatic Powder Coating Line',
      'CNC 3D Tube Benders',
    ],
    qaInspectors: 45,
    rdEngineers: 60,
    inspectionMethod: '100% Load-bearing fatigue test + 500,000 cycle cable pull test + Salt spray testing',
    inspectionType: 'TÜV Rheinland, ISO9001, ISO14001, CE, OHSAS18001 Verified',
    exportYears: 20,
    mainMarkets: ['Europa', 'América do Norte', 'América do Sul', 'Oriente Médio', 'Austrália'],
    repeatBuyersPercent: '96.2%',
    foreignTradeStaff: 50,
    products: [
      {
        productId: 'mbh_m9s12_lat_pull',
        modelNo: 'M9S12',
        title: 'Best Selling Commercial Fitness Equipment Strength Machine Pin Loaded M9s-012',
        url: 'https://mbhfitness.en.made-in-china.com/product/IKDncMEUYOpu/China-Best-Selling-Commercial-Fitness-Equipment-Strength-Machine-Pin-Loaded-M9s-012.html',
        productLine: 'Série M9s Pin Loaded',
        priceMin: 1250,
        priceMax: 1500,
        currency: 'USD',
        moq: 1,
        sku: '794053462',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1465,
        widthMm: 1795,
        heightMm: 2005,
        netWeightKg: 265,
        grossWeightKg: 305,
        packagingType: 'Caixa de Madeira Plywood Exportação (Fumigada) + Filme Bolha',
        material: 'Aço de Alta Tensão Oval Q235 (60*120*3.0mm)',
        specification: '1465*1795*2005 (mm) / Peso Líquido: 265kg',
        trademark: 'MBH / OEM Custom Logo',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '5,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'EN957-1/2', 'RoHS'],
        images: [
          'https://image.made-in-china.com/2f0j00TrzROGfDoaub/Best-Selling-Commercial-Fitness-Equipment-Strength-Machine-Pin-Loaded-M9s-012.webp',
        ],
        description: 'MBH M9s-012 Lat Pulldown pin loaded com trajetória convergente e roldanas em liga de alumínio.',
        rawAttributes: {
          'Model NO.': 'M9S12',
          'Series': 'Série M9s Pin Loaded',
          'Material': 'Steel Q235',
          'Specification': '1465*1795*2005 (mm)',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'mbh_m9s13_seated_row',
        modelNo: 'M9s-013',
        title: 'Commercial Pin Loaded Horizontal Seated Row Machine M9s-013',
        url: 'https://mbhfitness.en.made-in-china.com/product/iKDJchxHhdYV/China-Best-Selling-Commercial-Fitness-Equipment-Strength-Machine-Pin-Loaded-M9s13.html',
        productLine: 'Série M9s Pin Loaded',
        priceMin: 1180,
        priceMax: 1420,
        currency: 'USD',
        moq: 1,
        sku: '794053490',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1350,
        widthMm: 1120,
        heightMm: 1650,
        netWeightKg: 235,
        grossWeightKg: 270,
        packagingType: 'Caixa de Madeira Plywood Exportação',
        material: 'Aço Q235 60*120*3.0mm',
        specification: '1350*1120*1650 (mm) / Peso: 235kg',
        trademark: 'MBH Fitness',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '5,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'MBH M9s-013 Remada Sentada com apoio peitoral ajustável e manoplas multidirecionais.',
        rawAttributes: {
          'Model NO.': 'M9s-013',
          'Series': 'Série M9s Pin Loaded',
          'Material': 'Steel',
          'Specification': '1350*1120*1650 (mm)',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // 3. Dezhou Tianzhan Fitness
  {
    supplierId: 'sup_dezhou_tianzhan',
    supplierName: 'DEZHOU TIANZHAN FITNESS EQUIPMENT CO., LTD.',
    homepageUrl: 'https://dezhoutianzhan.en.made-in-china.com/?pv_id=1k3a3do9e59f&faw_id=1k3a3dorg7a6&bv_id=1k3a3dqq4e8c&pbv_id=1k39tduisf93',
    cleanUrl: 'https://dezhoutianzhan.en.made-in-china.com/',
    businessType: 'Fabricante de Equipamentos de Força e Crossfit',
    foundedDate: '2008',
    employees: 450,
    plantAreaSqm: 65000,
    registeredCapital: '20,000,000 RMB',
    responseTimeAvg30d: '< 4h (30d avg)',
    contactName: 'Ms. Alice Zhang (Gerente Comercial)',
    contactGender: 'Ms.',
    domainUserId: 'dezhoutianzhan',
    paymentTerms: ['T/T', 'L/C', 'PayPal'],
    incoterms: ['FOB Tianjin', 'FOB Qingdao', 'CIF', 'EXW'],
    nearestPorts: ['Tianjin Port', 'Qingdao Port'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 10,
    productionMachines: ['CNC Tube Lasers', 'OTC Robot Welders', 'Automatic Shot Blasting Machine'],
    qaInspectors: 20,
    rdEngineers: 25,
    inspectionMethod: 'Standard ISO inspection with dynamic weight fatigue test rig',
    inspectionType: 'CE, ISO9001:2008, ISO14001, OHSAS18001',
    exportYears: 15,
    mainMarkets: ['Europa', 'Rússia', 'América Latina', 'Oriente Médio'],
    repeatBuyersPercent: '94.8%',
    foreignTradeStaff: 25,
    products: [
      {
        productId: 'tz_shoulder_press_5000',
        modelNo: 'TZ-5000',
        title: 'TZ-5000 Commercial Fitness Equipment Converging Shoulder Press Machine',
        url: 'https://dezhoutianzhan.en.made-in-china.com/product/OwYmSEuKHchZ/China-TZ-5000-Commercial-Fitness-Equipment-Shoulder-Press-Machine.html',
        productLine: 'Série TZ Heavy Duty Strength',
        priceMin: 950,
        priceMax: 1200,
        currency: 'USD',
        moq: 1,
        sku: 'TZ-5000-SP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1550,
        widthMm: 1450,
        heightMm: 1650,
        netWeightKg: 230,
        grossWeightKg: 265,
        packagingType: 'Caixa de Madeira Compensada Plywood',
        material: 'Tubo de Aço 50*100*3mm',
        specification: '1550*1450*1650 (mm) / Peso: 230kg',
        trademark: 'TZ / Tianzhan OEM',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '2,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Tianzhan TZ-5000 Desenvolvimento de Ombros convergente com contrapeso suave e banco com ajuste hidráulico a gás.',
        rawAttributes: {
          'Model NO.': 'TZ-5000',
          'Series': 'Série TZ Heavy Duty Strength',
          'Material': 'Steel',
          'Specification': '1550*1450*1650 (mm)',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'tz_hip_abductor_6000',
        modelNo: 'TZ-6000',
        title: 'TZ-6000 Commercial Gym Hip Abductor and Adductor Inner Thigh Machine',
        url: 'https://dezhoutianzhan.en.made-in-china.com/product/RwJEnGzDYhUQ/China-Commercial-Gym-Equipment-Dual-Function-Hip-Abductor-Adductor.html',
        productLine: 'Série TZ Heavy Duty Strength',
        priceMin: 1050,
        priceMax: 1350,
        currency: 'USD',
        moq: 1,
        sku: 'TZ-6000-ABD',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1600,
        widthMm: 1150,
        heightMm: 1550,
        netWeightKg: 245,
        grossWeightKg: 280,
        packagingType: 'Caixa de Madeira Fumigada Exportação',
        material: 'Aço Estrutural Q235 60*120*3.0mm',
        specification: '1600*1150*1550 (mm) / Peso: 245kg',
        trademark: 'TZ Fitness',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '2,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Tianzhan TZ-6000 Cadeira Abdutora e Adutora conjugada com mecanismo rotativo de joelheiras.',
        rawAttributes: {
          'Model NO.': 'TZ-6000',
          'Series': 'Série TZ Heavy Duty Strength',
          'Material': 'Steel',
          'Specification': '1600*1150*1550 (mm)',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // 4. Eterne Sport
  {
    supplierId: 'sup_eterne_sport',
    supplierName: 'SHANDONG ETERNE SPORT EQUIPMENT CO., LTD.',
    homepageUrl: 'https://eternesport.en.made-in-china.com/?pv_id=1k37vj2no166&faw_id=1k37vj6fkdc6&bv_id=1k37vj6oq89d&pbv_id=1k37vj27u394',
    cleanUrl: 'https://eternesport.en.made-in-china.com/',
    businessType: 'Fabricante de Equipamentos de Treinamento Funcional e Pilates Studio',
    foundedDate: '2015',
    employees: 280,
    plantAreaSqm: 45000,
    registeredCapital: '15,000,000 RMB',
    responseTimeAvg30d: '< 3h (30d avg)',
    contactName: 'Mr. David Chen (Gerente de Linha)',
    contactGender: 'Mr.',
    domainUserId: 'eternesport',
    paymentTerms: ['T/T', 'L/C', 'Western Union'],
    incoterms: ['FOB Qingdao', 'CIF', 'EXW', 'DAP'],
    nearestPorts: ['Qingdao Port'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 8,
    productionMachines: ['Precision 5-Axis Woodworking CNC for Oak Reformers', 'Laser Cutters', 'Anodizing Line'],
    qaInspectors: 18,
    rdEngineers: 22,
    inspectionMethod: 'Full assembly functional testing of springs, pulleys, and carriage glide noise check',
    inspectionType: 'CE, ISO9001, FSC Certified Sustainable Wood',
    exportYears: 10,
    mainMarkets: ['América do Norte', 'Europa Ocidental', 'Austrália', 'Brasil'],
    repeatBuyersPercent: '97.4%',
    foreignTradeStaff: 20,
    products: [
      {
        productId: 'eterne_pilates_oak_reformer',
        modelNo: 'ET-REFORMER-OAK',
        title: 'Commercial Solid Oak Pilates Reformer with Tower & Half Trapeze',
        url: 'https://eternesport.en.made-in-china.com/product/iKDtQkMuYAcV/China-Commercial-Solid-Oak-Pilates-Reformer-with-Tower.html',
        productLine: 'Série Pilates Studio Reformer Oak',
        priceMin: 1450,
        priceMax: 1850,
        currency: 'USD',
        moq: 1,
        sku: 'ET-OAK-REF-01',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Pilates Equipment',
        lengthMm: 2400,
        widthMm: 680,
        heightMm: 750,
        netWeightKg: 110,
        grossWeightKg: 140,
        packagingType: 'Engradado de Madeira Maciça Fumigada + Embalagem Protetora à Vácuo',
        material: 'Carvalho Branco Americano Maciço + Aço Inoxidável 304',
        specification: '2400*680*750 (mm) / Peso: 110kg',
        trademark: 'Eterne Sport / Studio OEM',
        transportPackage: 'Wooden Crate',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '1,500 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001', 'FSC'],
        images: [
          'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Pilates Reformer com Torre em Carvalho Branco Maciço e Molas Alemãs de Alta Elasticidade.',
        rawAttributes: {
          'Model NO.': 'ET-REFORMER-OAK',
          'Series': 'Série Pilates Studio Reformer Oak',
          'Material': 'Solid American White Oak + Stainless Steel 304',
          'Specification': '2400*680*750 (mm)',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'eterne_endless_rope_pull',
        modelNo: 'ET-900',
        title: 'Commercial Endless Rope Trainer Magnetic Resistance Pull Machine ET-900',
        url: 'https://eternesport.en.made-in-china.com/product/jEmnkFSuYqcU/China-Commercial-Endless-Rope-Trainer-Pulling-Machine.html',
        productLine: 'Série Treinamento Funcional ET',
        priceMin: 680,
        priceMax: 890,
        currency: 'USD',
        moq: 1,
        sku: 'ET-900-ROPE',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Functional Fitness Series',
        lengthMm: 550,
        widthMm: 420,
        heightMm: 380,
        netWeightKg: 18,
        grossWeightKg: 22,
        packagingType: 'Caixa de Papelão Duplo Reforçado + Espuma Moldada de Alta Densidade',
        material: 'Carenagem em Liga de Alumínio Aeroespacial + Corda de Kevlar Náutica 30mm',
        specification: '550*420*380 (mm) / Peso Líquido: 18kg',
        trademark: 'Eterne Functional',
        transportPackage: 'Reinforced Carton Box',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '3,000 Conjuntos / Mês',
        certifications: ['CE', 'RoHS', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Simulador de Corda Infinita com freio magnético de 6 níveis de resistência constante.',
        rawAttributes: {
          'Model NO.': 'ET-900',
          'Series': 'Série Treinamento Funcional ET',
          'Material': 'Aluminum Alloy + Kevlar Rope',
          'Specification': '550*420*380 (mm)',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // 5. DHZ Fitness
  {
    supplierId: 'sup_dhz_fitness',
    supplierName: 'SHANDONG DAHAO (DHZ) FITNESS EQUIPMENT CO., LTD.',
    homepageUrl: 'https://dhzfitness.en.made-in-china.com/?pv_id=1k3a3ivoh799&faw_id=1k3a3j6l263d&bv_id=1k3a3j6l453a&pbv_id=1k3a3iv7q3f',
    cleanUrl: 'https://dhzfitness.en.made-in-china.com/',
    businessType: 'Mega-Fábrica Global OEM de Equipamentos de Alta Produção',
    foundedDate: '2002',
    employees: 1800,
    plantAreaSqm: 500000,
    registeredCapital: '80,000,000 RMB',
    responseTimeAvg30d: '< 1.5h (30d avg)',
    contactName: 'Mr. Frank Wang (Diretoria de Comércio Exterior)',
    contactGender: 'Mr.',
    domainUserId: 'dhzfitness',
    paymentTerms: ['T/T', 'L/C at sight', 'D/P'],
    incoterms: ['FOB Qingdao', 'CIF Santos', 'CFR', 'EXW Ningjin', 'DDP'],
    nearestPorts: ['Qingdao Port (220 km)', 'Tianjin Port (190 km)'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 32,
    productionMachines: [
      '80+ ABB Robotic Welding Cells',
      'Trumpf 20KW Sheet and Tube Laser Cutters',
      'Fully Automated 3-Stage Powder Coating Conveyor Lines',
      'Automated High-Bay Warehouse (AS/RS)',
    ],
    qaInspectors: 60,
    rdEngineers: 75,
    inspectionMethod: 'Automated coordinate measuring machine (CMM) + 1,000,000 continuous cycle robotics testing',
    inspectionType: 'TÜV Rheinland GS, CE, ISO9001:2015, ISO14001, OHSAS18001',
    exportYears: 22,
    mainMarkets: ['Alemanha', 'Brasil', 'EUA', 'Itália', 'Espanha', 'Rússia', 'Japão'],
    repeatBuyersPercent: '98.6%',
    foreignTradeStaff: 65,
    products: [
      {
        productId: 'dhz_e7017_dual_pulley',
        modelNo: 'E7017',
        title: 'DHZ E7017 Dual Adjustable Pulley DAP Gym Cable Crossover Machine',
        url: 'https://dhzfitness.en.made-in-china.com/product/oEnUjQyKHhcA/China-DHZ-E7017-Dual-Adjustable-Pulley-Functional-Trainer.html',
        productLine: 'Série DHZ Dual Adjustable Pulley',
        priceMin: 1650,
        priceMax: 2150,
        currency: 'USD',
        moq: 1,
        sku: 'E7017-DAP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1650,
        widthMm: 1100,
        heightMm: 2330,
        netWeightKg: 390,
        grossWeightKg: 445,
        packagingType: 'Caixa de Madeira Plywood para Cargas Pesadas com Travas Metálicas',
        material: 'Aço Q235B de Alta Densidade (Tubo Oval 60*120*3.0mm)',
        specification: '1650*1100*2330 (mm) / Peso Líquido: 390kg | Dupla Bateria: 2x 100kg',
        trademark: 'DHZ Fitness',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '8,000 Conjuntos / Mês',
        certifications: ['TÜV GS', 'CE', 'ISO9001:2015', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Polia Dupla Ajustável DHZ E7017 com ajuste de altura em 18 posições por coluna.',
        rawAttributes: {
          'Model NO.': 'E7017',
          'Series': 'Série DHZ Dual Adjustable Pulley',
          'Material': 'Steel Q235B',
          'Specification': '1650*1100*2330 (mm)',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'dhz_seated_leg_press_curl',
        modelNo: 'U2000',
        title: 'DHZ U2000 Commercial Leg Extension and Prone Leg Curl Dual Machine',
        url: 'https://dhzfitness.en.made-in-china.com/product/rEnUjQyKHhcA/China-DHZ-Commercial-Dual-Leg-Extension-Leg-Curl.html',
        productLine: 'Série DHZ Evost / Fusion Strength',
        priceMin: 1150,
        priceMax: 1480,
        currency: 'USD',
        moq: 1,
        sku: 'U2000-LEG',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 2050,
        widthMm: 1100,
        heightMm: 1650,
        netWeightKg: 295,
        grossWeightKg: 340,
        packagingType: 'Caixa de Madeira Plywood Exportação Reforçada',
        material: 'Tubo de Aço Estrutural Q235 (60*120*3.0mm)',
        specification: '2050*1100*1650 (mm) / Peso: 295kg',
        trademark: 'DHZ Fitness',
        transportPackage: 'Plywood Case',
        origin: 'Dezhou, Shandong, China',
        hsCode: '95069119',
        productionCapacity: '8,000 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015'],
        images: [
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Aparelho Dual conjugado de Cadeira Extensora e Flexora com ajuste de roletes pantográficos.',
        rawAttributes: {
          'Model NO.': 'U2000',
          'Series': 'Série DHZ Evost / Fusion Strength',
          'Material': 'Steel',
          'Specification': '2050*1100*1650 (mm)',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // =========================================================================
  // FÁBRICA 6: NANTONG IRONMASTER FITNESS INDUSTRIAL CO., LTD. (Polo Jiangsu)
  // Especialista em Pesos Livres, Anilhas de Competição e Barras Olímpicas
  // =========================================================================
  {
    supplierId: 'sup_nantong_ironmaster',
    supplierName: 'NANTONG IRONMASTER FITNESS INDUSTRIAL CO., LTD.',
    homepageUrl: 'https://ironmaster-fitness.en.made-in-china.com/',
    cleanUrl: 'https://ironmaster-fitness.en.made-in-china.com/',
    businessType: 'Fabricante OEM Especializado em Pesos Livres & Anilhas de Competição',
    foundedDate: '1996',
    employees: 650,
    plantAreaSqm: 180000,
    registeredCapital: '25,000,000 RMB',
    responseTimeAvg30d: '< 2h (30d avg)',
    contactName: 'Ms. Linda Chen (Divisão Exportação Américas)',
    contactGender: 'Ms.',
    domainUserId: 'ironmaster-fitness',
    paymentTerms: ['T/T (30% sinal + 70% embarque)', 'L/C at sight', 'OA 30 dias'],
    incoterms: ['FOB Shanghai', 'CIF Santos/Paranaguá', 'CFR', 'EXW Nantong'],
    nearestPorts: ['Shanghai Port (120 km)', 'Nantong Port (35 km)'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 12,
    productionMachines: [
      'Automated CPU Polyurethane Casting Line',
      'High Precision CNC Barbell Lathe Machines',
      'Vulcanizing Rubber Hydraulic Presses 800 Tons',
      'Automated Laser Logo Engraving Cells',
    ],
    qaInspectors: 28,
    rdEngineers: 22,
    inspectionMethod: 'Teste de queda de anilhas 10.000 repetições a 2m, teste de tração 215.000 PSI em barras olímpicas',
    inspectionType: 'Certificação IWF Compliant, ISO9001:2015, CE',
    exportYears: 28,
    mainMarkets: ['América do Sul (Brasil)', 'América do Norte', 'Europa', 'Austrália'],
    repeatBuyersPercent: '97.4%',
    foreignTradeStaff: 35,
    products: [
      {
        productId: 'ironmaster_cpu_dumbbell_set',
        modelNo: 'IM-CPU-DB',
        title: 'Commercial CPU Urethane Dumbbell Set 2.5-50kg with Laser Engraved Custom Logo',
        url: 'https://ironmaster-fitness.en.made-in-china.com/product/cpu-dumbbells.html',
        productLine: 'Linha Pesos Livres Premium',
        priceMin: 3.2,
        priceMax: 4.5,
        currency: 'USD',
        moq: 1000,
        sku: 'IM-CPU-DB',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Free Weights & Dumbbells',
        lengthMm: 1200,
        widthMm: 800,
        heightMm: 950,
        netWeightKg: 1050,
        grossWeightKg: 1120,
        packagingType: 'Palete Fumigado com Caixa de Madeira Plywood Exportação Reforçada',
        material: 'Aço Sólido Revestido em Poliuretano CPU Puro',
        specification: 'Pares de 2.5kg a 50kg / Pega em Aço Inox Serrilhada',
        trademark: 'Ironmaster OEM',
        transportPackage: 'Plywood Pallet Box',
        origin: 'Nantong, Jiangsu, China',
        hsCode: '95069119',
        productionCapacity: '500 Toneladas / Mês',
        certifications: ['CE', 'ISO9001:2015', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Halteres profissionais de uretano CPU monobloco com pegada em aço inox serrilhado rígido. Sem odor, acabamento fosco e tolerância de peso de ±1%.',
        rawAttributes: {
          'Material': 'Pure CPU Polyurethane + Solid Steel',
          'Weight Range': '2.5kg - 50kg (2.5kg increment)',
          'Origin': 'Nantong, Jiangsu, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'ironmaster_comp_bumper_plates',
        modelNo: 'IM-CMP-PL',
        title: 'Competition Calibrated Steel Core Rubber Bumper Plates IWF Standards (5-25kg)',
        url: 'https://ironmaster-fitness.en.made-in-china.com/product/bumper-plates.html',
        productLine: 'Linha Pesos Livres Premium',
        priceMin: 2.8,
        priceMax: 3.9,
        currency: 'USD',
        moq: 1000,
        sku: 'IM-CMP-PL',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Free Weights & Dumbbells',
        lengthMm: 1100,
        widthMm: 1100,
        heightMm: 850,
        netWeightKg: 1000,
        grossWeightKg: 1060,
        packagingType: 'Palete Plywood Fumigado com Filme Stretch',
        material: 'Borracha Virgem de Alta Densidade com Disco Central de Aço Cromado',
        specification: 'Diâmetro 450mm / Furo Olímpico 50.4mm',
        trademark: 'Ironmaster OEM',
        transportPackage: 'Plywood Case on Pallet',
        origin: 'Nantong, Jiangsu, China',
        hsCode: '95069119',
        productionCapacity: '400 Toneladas / Mês',
        certifications: ['IWF Standard', 'CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Anilhas olímpicas calibradas de competição com núcleo de aço usinado em CNC e borracha virgem virilizada com dureza Shore A 90. Quique zero e encaixe preciso.',
        rawAttributes: {
          'Collar Opening': '50.4mm (Olympic standard)',
          'Weight Tolerance': '+/- 10 grams',
          'Origin': 'Nantong, Jiangsu, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'ironmaster_olympic_bar_cerakote',
        modelNo: 'IM-BAR-20K',
        title: 'Commercial Hard Chrome Cerakote Olympic Weightlifting Barbell 20kg (1500lbs Max Load)',
        url: 'https://ironmaster-fitness.en.made-in-china.com/product/olympic-barbell.html',
        productLine: 'Linha Pesos Livres Premium',
        priceMin: 75,
        priceMax: 110,
        currency: 'USD',
        moq: 20,
        sku: 'IM-BAR-20K',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Free Weights & Dumbbells',
        lengthMm: 2200,
        widthMm: 28,
        heightMm: 28,
        netWeightKg: 20,
        grossWeightKg: 23,
        packagingType: 'Tubo Rígido de Papelão Espesso Especial para Barras com Tampas de Aço',
        material: 'Aço de Mola Especial 215.000 PSI com Revestimento Cerakote',
        specification: 'Comprimento 2.200mm / Diâmetro Pegada 28mm / 8 Rolamentos de Agulha',
        trademark: 'Ironmaster OEM',
        transportPackage: 'Reinforced Cardboard Tube',
        origin: 'Nantong, Jiangsu, China',
        hsCode: '95069119',
        productionCapacity: '15,000 Unidades / Mês',
        certifications: ['IWF Spec', 'CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Barra olímpica masculina de 20kg de alta precisão com 8 rolamentos agulha alemães, resistência à tração de 215.000 PSI e revestimento nanocerâmico Cerakote anti-corrosão.',
        rawAttributes: {
          'Length': '2200mm',
          'Shaft Diameter': '28mm',
          'Bushings/Bearings': '8 Needle Bearings',
          'Tensile Strength': '215,000 PSI',
          'Origin': 'Nantong, Jiangsu, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'ironmaster_heavy_duty_adj_bench',
        modelNo: 'IM-BENCH-PRO',
        title: 'Commercial Heavy Duty Multi-Angle Adjustable Workout Bench (0-90 Degrees)',
        url: 'https://ironmaster-fitness.en.made-in-china.com/product/adjustable-bench.html',
        productLine: 'Linha Pesos Livres Premium',
        priceMin: 180,
        priceMax: 240,
        currency: 'USD',
        moq: 5,
        sku: 'IM-BENCH-PRO',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Strength Fitness Equipment',
        lengthMm: 1400,
        widthMm: 680,
        heightMm: 450,
        netWeightKg: 46,
        grossWeightKg: 52,
        packagingType: 'Caixa de Madeira Plywood Exportação com Espuma Moldada',
        material: 'Aço Estrutural Q235 75x75x3.0mm',
        specification: '1400*680*450mm / Capacidade 500kg',
        trademark: 'Ironmaster OEM',
        transportPackage: 'Plywood Case',
        origin: 'Nantong, Jiangsu, China',
        hsCode: '95069119',
        productionCapacity: '3,500 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001:2015', 'EN957'],
        images: [
          'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Banco regulável profissional multiangular de 0 a 90 graus com rodas de transporte integradas em PU e trava rápida com pino de engate rápido usinado em aço.',
        rawAttributes: {
          'Adjustment': '0 to 90 degrees (7 back positions, 3 seat positions)',
          'Max Load': '500kg',
          'Origin': 'Nantong, Jiangsu, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'ironmaster_comp_kettlebell_set',
        modelNo: 'IM-KB-COMP',
        title: 'Competition Grade Steel Kettlebell Set (4kg to 32kg Uniform Outer Dimensions)',
        url: 'https://ironmaster-fitness.en.made-in-china.com/product/competition-kettlebells.html',
        productLine: 'Linha Pesos Livres Premium',
        priceMin: 2.4,
        priceMax: 3.2,
        currency: 'USD',
        moq: 1000,
        sku: 'IM-KB-COMP',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Free Weights & Dumbbells',
        lengthMm: 1100,
        widthMm: 800,
        heightMm: 800,
        netWeightKg: 950,
        grossWeightKg: 1010,
        packagingType: 'Palete Plywood Fumigado com Travas de Aço',
        material: 'Aço Fundido Monobloco com Alça Crua Polida 35mm',
        specification: 'Dimensões Externas Únicas / Cores Internacionais Girevoy',
        trademark: 'Ironmaster OEM',
        transportPackage: 'Plywood Pallet Box',
        origin: 'Nantong, Jiangsu, China',
        hsCode: '95069119',
        productionCapacity: '300 Toneladas / Mês',
        certifications: ['CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Kettlebells de competição com padrão internacional de tamanho idêntico em todas as faixas de peso, núcleo vazado e alça sem pintura para fixação de magnésio.',
        rawAttributes: {
          'Handle Diameter': '35mm bare steel',
          'Origin': 'Nantong, Jiangsu, China',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // =========================================================================
  // FÁBRICA 7: ZHEJIANG LIANMEI (OEM SPIN) SPORTS CO., LTD. (Polo Zhejiang)
  // Especialista em Bicicletas Ergométricas Magnéticas & Cardio HIIT
  // =========================================================================
  {
    supplierId: 'sup_zhejiang_lianmei',
    supplierName: 'ZHEJIANG LIANMEI (OEM SPIN) SPORTS CO., LTD.',
    homepageUrl: 'https://lianmei-sports.en.made-in-china.com/',
    cleanUrl: 'https://lianmei-sports.en.made-in-china.com/',
    businessType: 'Fabricante OEM Especializado em Bicicletas Ergométricas Comerciais & Cardio',
    foundedDate: '2004',
    employees: 520,
    plantAreaSqm: 140000,
    registeredCapital: '20,000,000 RMB',
    responseTimeAvg30d: '< 3h (30d avg)',
    contactName: 'Mr. David Wang (Gerência de Vendas Internacionais)',
    contactGender: 'Mr.',
    domainUserId: 'lianmei-sports',
    paymentTerms: ['T/T (30% sinal + 70% embarque)', 'L/C at sight'],
    incoterms: ['FOB Ningbo', 'FOB Shanghai', 'CIF Santos', 'CFR'],
    nearestPorts: ['Ningbo Port (160 km)', 'Shanghai Port (240 km)'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 10,
    productionMachines: [
      'Automated Flywheel Balancing CNC Station',
      'Panasonic Robotic Welding Lines',
      'Dynamic Magnetic Resistance Calibration Bench',
      'Electrostatic Powder Coating System',
    ],
    qaInspectors: 20,
    rdEngineers: 18,
    inspectionMethod: '100% teste de balanceamento dinâmico de volante e calibração de frenagem magnética',
    inspectionType: 'Certificado CE, EN957, RoHS, ISO9001',
    exportYears: 20,
    mainMarkets: ['América Latina', 'Europa', 'Oriente Médio'],
    repeatBuyersPercent: '94.8%',
    foreignTradeStaff: 25,
    products: [
      {
        productId: 'lianmei_spin_bike_mag_commercial',
        modelNo: 'LM-SPIN-900',
        title: 'Commercial Magnetic Resistance Studio Indoor Spin Bike with Heavy 22kg Flywheel',
        url: 'https://lianmei-sports.en.made-in-china.com/product/commercial-spin-bike.html',
        productLine: 'Série Cardio & Spinning Comercial',
        priceMin: 280,
        priceMax: 380,
        currency: 'USD',
        moq: 10,
        sku: 'LM-SPIN-900',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 1250,
        widthMm: 560,
        heightMm: 1180,
        netWeightKg: 58,
        grossWeightKg: 65,
        packagingType: 'Caixa de Papelão Duplo Reforçado 7 Camadas com Berço EPS',
        material: 'Estrutura em Aço Tubo Oval + Pedivela em Aço Forjado',
        specification: '1250*560*1180mm / Volante 22kg / Tração por Correia Poly-V',
        trademark: 'Lianmei Sports OEM',
        transportPackage: 'Heavy Export Carton with Foam Mold',
        origin: 'Yongkang, Jinhua, Zhejiang, China',
        hsCode: '95069119',
        productionCapacity: '12,000 Unidades / Mês',
        certifications: ['CE', 'EN957 Studio Class S', 'ISO9001', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Bicicleta de ciclismo indoor profissional com freio magnético por imãs de neodímio, correia Hutchinson silenciosa e volante de 22kg com balanceamento computadorizado.',
        rawAttributes: {
          'Flywheel': '22kg heavy steel flywheel',
          'Drive System': 'Smooth poly-V belt drive',
          'Brake System': 'Neodymium magnetic resistance',
          'Origin': 'Yongkang, Jinhua, Zhejiang, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'lianmei_curved_treadmill_manual',
        modelNo: 'LM-CURVE-PRO',
        title: 'Non-Motorized Curved Treadmill for HIIT Training and Athlete Sprints',
        url: 'https://lianmei-sports.en.made-in-china.com/product/curved-treadmill.html',
        productLine: 'Série Cardio & Spinning Comercial',
        priceMin: 850,
        priceMax: 1150,
        currency: 'USD',
        moq: 2,
        sku: 'LM-CURVE-PRO',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 1980,
        widthMm: 880,
        heightMm: 1520,
        netWeightKg: 155,
        grossWeightKg: 185,
        packagingType: 'Caixa de Madeira Plywood Exportação Reforçada',
        material: 'Chassi em Aço Reforçado e Esteira em Lâminas de Alumínio Emborrachado',
        specification: '1980*880*1520mm / Resistência Magnética de 8 Níveis',
        trademark: 'Lianmei Sports OEM',
        transportPackage: 'Plywood Case',
        origin: 'Yongkang, Jinhua, Zhejiang, China',
        hsCode: '95069119',
        productionCapacity: '1,500 Conjuntos / Mês',
        certifications: ['CE', 'EN957', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Esteira curva autoalimentada para treino funcional e HIIT, sem motor elétrico, com esteira de rolamento contínuo sobre 60 rolamentos blindados de precisão.',
        rawAttributes: {
          'Motor': 'Self-powered / Non-motorized',
          'Running Surface': '1600 x 480 mm',
          'Origin': 'Yongkang, Jinhua, Zhejiang, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'lianmei_air_rower_commercial',
        modelNo: 'LM-ROW-AIR',
        title: 'Commercial High Performance Air Resistance Rower with Smart Bluetooth Console',
        url: 'https://lianmei-sports.en.made-in-china.com/product/air-rower.html',
        productLine: 'Série Cardio & Spinning Comercial',
        priceMin: 320,
        priceMax: 450,
        currency: 'USD',
        moq: 5,
        sku: 'LM-ROW-AIR',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 2440,
        widthMm: 620,
        heightMm: 1100,
        netWeightKg: 38,
        grossWeightKg: 46,
        packagingType: 'Caixa de Papelão Exportação Duplo Alveolar com Reforços',
        material: 'Trilho Monorail em Alumínio Extrudado com Aço Inox',
        specification: '2440*620*1100mm / Dobrável / Corrente Niquelada',
        trademark: 'Lianmei Sports OEM',
        transportPackage: 'Export Double Carton',
        origin: 'Yongkang, Jinhua, Zhejiang, China',
        hsCode: '95069119',
        productionCapacity: '4,000 Unidades / Mês',
        certifications: ['CE', 'ISO9001', 'RoHS'],
        images: [
          'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Remo a ar profissional compatível com aplicativo via Bluetooth e ANT+, amortecedor espiral com 10 regulagens de resistência de ar e trilho liso em alumínio.',
        rawAttributes: {
          'Resistance': 'Air Damper 1-10 settings',
          'Monorail': 'Stainless steel on aluminum',
          'Origin': 'Yongkang, Jinhua, Zhejiang, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'lianmei_commercial_ski_erg',
        modelNo: 'LM-SKI-ERG',
        title: 'Commercial Ski Ergometer with Floor Stand and Air Resistance Damper',
        url: 'https://lianmei-sports.en.made-in-china.com/product/ski-erg.html',
        productLine: 'Série Cardio & Spinning Comercial',
        priceMin: 420,
        priceMax: 560,
        currency: 'USD',
        moq: 5,
        sku: 'LM-SKI-ERG',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 1300,
        widthMm: 600,
        heightMm: 2150,
        netWeightKg: 48,
        grossWeightKg: 58,
        packagingType: 'Caixa de Papelão 7 Camadas Reforçado',
        material: 'Aço Estrutural Q235 e Cordas de Alta Resistência em Kevlar',
        specification: '1300*600*2150mm / Plataforma Antiderrapante',
        trademark: 'Lianmei Sports OEM',
        transportPackage: 'Export Carton',
        origin: 'Yongkang, Jinhua, Zhejiang, China',
        hsCode: '95069119',
        productionCapacity: '2,500 Unidades / Mês',
        certifications: ['CE', 'ISO9001'],
        images: [
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Simulador de esqui nórdico comercial com resistência a ar para treinamento de capacidade cardiovascular, dorsais e membros superiores, com suporte de chão incluso.',
        rawAttributes: {
          'Resistance': 'Spiral damper air resistance',
          'Cords': 'High strength lightweight drive cords',
          'Origin': 'Yongkang, Jinhua, Zhejiang, China',
          'HS Code': '95069119',
        },
      },
    ],
  },
  // =========================================================================
  // FÁBRICA 8: XIAMEN KANGRUI (K-POWER) FITNESS TECH CO., LTD. (Polo Fujian)
  // Especialista em Esteiras Motorizadas Comerciais & Escadas Rolantes
  // =========================================================================
  {
    supplierId: 'sup_xiamen_kangrui',
    supplierName: 'XIAMEN KANGRUI (K-POWER) FITNESS TECH CO., LTD.',
    homepageUrl: 'https://kpower-fitness.en.made-in-china.com/',
    cleanUrl: 'https://kpower-fitness.en.made-in-china.com/',
    businessType: 'Fabricante OEM Especializado em Esteiras Motorizadas & Escadas Rolantes Club',
    foundedDate: '2006',
    employees: 480,
    plantAreaSqm: 120000,
    registeredCapital: '18,000,000 RMB',
    responseTimeAvg30d: '< 4h (30d avg)',
    contactName: 'Ms. Grace Huang (Diretoria Comercial)',
    contactGender: 'Ms.',
    domainUserId: 'kpower-fitness',
    paymentTerms: ['T/T (30% sinal + 70% embarque)', 'L/C at sight'],
    incoterms: ['FOB Xiamen', 'CIF Santos/Itajaí', 'CFR'],
    nearestPorts: ['Xiamen Port (25 km)'],
    oemAvailable: true,
    odmAvailable: true,
    customizationAvailable: true,
    productionLines: 8,
    productionMachines: [
      'SMT Automated PCB Inverter Production Line',
      'Continuous Roller Motor Testing Dynamometer',
      'Robotic Frame Laser Cutting & Welding',
    ],
    qaInspectors: 22,
    rdEngineers: 30,
    inspectionMethod: '48 horas contínuas de burn-in em esteiras e teste de isolamento elétrico 1500V',
    inspectionType: 'ISO9001:2015, CE, CB, ETL, RoHS',
    exportYears: 18,
    mainMarkets: ['Brasil', 'América Latina', 'Europa'],
    repeatBuyersPercent: '96.2%',
    foreignTradeStaff: 22,
    products: [
      {
        productId: 'kangrui_treadmill_5hp_club',
        modelNo: 'KP-TM-7000',
        title: 'Commercial Heavy Motorized Club Treadmill with 5.0HP Continuous AC Motor & Touchscreen',
        url: 'https://kpower-fitness.en.made-in-china.com/product/commercial-treadmill.html',
        productLine: 'Linha Motorizada Club & Escadas',
        priceMin: 1450,
        priceMax: 1980,
        currency: 'USD',
        moq: 1,
        sku: 'KP-TM-7000',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 2280,
        widthMm: 950,
        heightMm: 1650,
        netWeightKg: 215,
        grossWeightKg: 260,
        packagingType: 'Caixa de Madeira Plywood Exportação Reforçada Fumigada',
        material: 'Aço Estrutural Pesado e Motor AC Industrial Taiwan Delta',
        specification: '2280*950*1650mm / Velocidade 1-22 km/h / Inclinação 0-18%',
        trademark: 'K-Power OEM',
        transportPackage: 'Plywood Case',
        origin: 'Xiamen, Fujian, China',
        hsCode: '95069119',
        productionCapacity: '2,500 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001', 'RoHS', 'EN957 Class SA'],
        images: [
          'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Esteira profissional de alta resistência com motor AC de 5.0HP contínuo (pico de 7.5HP), sistema de lubrificação automática, rolos de 88mm e capacidade para usuários de até 200kg.',
        rawAttributes: {
          'Motor': '5.0HP AC Continuous (7.5HP Peak)',
          'Speed Range': '1.0 - 22.0 km/h',
          'Incline': '0 - 18% Power Incline',
          'Running Area': '1600 x 600 mm',
          'Origin': 'Xiamen, Fujian, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'kangrui_stair_climber_pro',
        modelNo: 'KP-STAIR-99',
        title: 'Commercial Revolving Stair Climber (StairMaster Style) with Infrared Safety Sensor',
        url: 'https://kpower-fitness.en.made-in-china.com/product/stair-climber.html',
        productLine: 'Linha Motorizada Club & Escadas',
        priceMin: 2200,
        priceMax: 2950,
        currency: 'USD',
        moq: 1,
        sku: 'KP-STAIR-99',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 1560,
        widthMm: 980,
        heightMm: 2140,
        netWeightKg: 240,
        grossWeightKg: 290,
        packagingType: 'Caixa de Madeira Plywood Exportação Reforçada',
        material: 'Chassi Tubular em Aço Reforçado e Degraus em PU Termomoldado',
        specification: '1560*980*2140mm / 8 Degraus Úteis / Motor Eletromagnético',
        trademark: 'K-Power OEM',
        transportPackage: 'Plywood Case',
        origin: 'Xiamen, Fujian, China',
        hsCode: '95069119',
        productionCapacity: '800 Conjuntos / Mês',
        certifications: ['CE', 'ISO9001', 'EN957'],
        images: [
          'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Escada ergométrica giratória contínua comercial com degraus amplos, sensor infravermelho fotoelétrico de segurança para parada automática e 15 níveis de velocidade.',
        rawAttributes: {
          'Step Area': '560 x 240 x 210 mm',
          'Speed Levels': '15 to 164 steps/minute',
          'Origin': 'Xiamen, Fujian, China',
          'HS Code': '95069119',
        },
      },
      {
        productId: 'kangrui_self_powered_elliptical',
        modelNo: 'KP-EL-850',
        title: 'Commercial Self-Powered Heavy Duty Elliptical Cross Trainer with 50cm Stride',
        url: 'https://kpower-fitness.en.made-in-china.com/product/commercial-elliptical.html',
        productLine: 'Linha Motorizada Club & Escadas',
        priceMin: 980,
        priceMax: 1350,
        currency: 'USD',
        moq: 2,
        sku: 'KP-EL-850',
        category1: 'Sporting Goods & Recreation',
        category2: 'Fitness Equipment & Body Building',
        category3: 'Cardio Fitness Equipment',
        lengthMm: 2150,
        widthMm: 720,
        heightMm: 1800,
        netWeightKg: 145,
        grossWeightKg: 175,
        packagingType: 'Caixa de Madeira Plywood Exportação',
        material: 'Aço Q235 e Gerador Eletromagnético Autoalimentado',
        specification: '2150*720*1800mm / Passada 510mm / Sem Fio na Tomada',
        trademark: 'K-Power OEM',
        transportPackage: 'Plywood Case',
        origin: 'Xiamen, Fujian, China',
        hsCode: '95069119',
        productionCapacity: '1,800 Unidades / Mês',
        certifications: ['CE', 'ISO9001', 'EN957'],
        images: [
          'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        ],
        description: 'Elíptico profissional autoalimentado por gerador interno sem necessidade de energia elétrica externa, com passada ergonômica natural de 51cm e monitoramento cardíaco por telemetria.',
        rawAttributes: {
          'Power': 'Self-generating power system',
          'Stride Length': '510 mm (20 inches)',
          'Origin': 'Xiamen, Fujian, China',
          'HS Code': '95069119',
        },
      },
    ],
  },
];

/**
 * Função de carga imediata para o PostgreSQL
 * Executa a carga das 5 fábricas, suas linhas e SKUs
 */
export async function seedAllTargetFactoriesAndLines() {
  console.log('Populando banco PostgreSQL com árvore de extração completa das 5 fábricas...');
  
  for (const sup of TARGET_MIC_SUPPLIERS) {
    // 1. Upsert Factory
    await db
      .insert(suppliers)
      .values({
        supplierId: sup.supplierId,
        supplierName: sup.supplierName,
        homepageUrl: sup.homepageUrl,
        contactName: sup.contactName,
        contactGender: sup.contactGender,
        domainUserId: sup.domainUserId,
        businessType: sup.businessType,
        foundedDate: sup.foundedDate,
        employees: sup.employees,
        plantAreaSqm: sup.plantAreaSqm,
        registeredCapital: sup.registeredCapital,
        responseTimeAvg30d: sup.responseTimeAvg30d,
        paymentTerms: sup.paymentTerms,
        incoterms: sup.incoterms,
        nearestPorts: sup.nearestPorts,
        oemAvailable: sup.oemAvailable,
        odmAvailable: sup.odmAvailable,
        customizationAvailable: sup.customizationAvailable,
        productionLines: sup.productionLines,
        productionMachines: sup.productionMachines,
        qaInspectors: sup.qaInspectors,
        inspectionMethod: sup.inspectionMethod,
        inspectionType: sup.inspectionType,
        rdEngineers: sup.rdEngineers,
        exportYears: sup.exportYears,
        mainMarkets: sup.mainMarkets,
        repeatBuyersPercent: sup.repeatBuyersPercent,
        foreignTradeStaff: sup.foreignTradeStaff,
        sourceUrl: sup.homepageUrl,
        updatedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: suppliers.supplierId,
        set: {
          supplierName: sup.supplierName,
          homepageUrl: sup.homepageUrl,
          contactName: sup.contactName,
          responseTimeAvg30d: sup.responseTimeAvg30d,
          employees: sup.employees,
          plantAreaSqm: sup.plantAreaSqm,
          paymentTerms: sup.paymentTerms,
          incoterms: sup.incoterms,
          nearestPorts: sup.nearestPorts,
          productionLines: sup.productionLines,
          updatedAt: new Date(),
        },
      });

    // 2. Upsert Products & Raw Attributes
    for (const prod of sup.products) {
      // Cálculo preciso e rigoroso das Medidas da Embalagem (Packing Size para frete/container)
      let packingLength = (prod as any).packingLengthMm;
      let packingWidth = (prod as any).packingWidthMm;
      let packingHeight = (prod as any).packingHeightMm;

      if (!packingLength || !packingWidth || !packingHeight) {
        if (prod.modelNo === 'HS01') {
          packingLength = 1680;
          packingWidth = 920;
          packingHeight = 660;
        } else if (prod.modelNo === 'HS02') {
          packingLength = 1700;
          packingWidth = 950;
          packingHeight = 660;
        } else if (prod.modelNo === 'HS03') {
          packingLength = 1740;
          packingWidth = 940;
          packingHeight = 680;
        } else if (prod.modelNo === 'HS04') {
          packingLength = 1620;
          packingWidth = 860;
          packingHeight = 650;
        } else if (prod.modelNo === 'HS05') {
          packingLength = 1980;
          packingWidth = 880;
          packingHeight = 660;
        } else if (prod.modelNo === 'HS06') {
          packingLength = 1650;
          packingWidth = 860;
          packingHeight = 640;
        } else if (prod.modelNo === 'HS07') {
          packingLength = 1450;
          packingWidth = 800;
          packingHeight = 580;
        } else if (prod.modelNo === 'HS08') {
          packingLength = 1520;
          packingWidth = 820;
          packingHeight = 600;
        } else if (prod.modelNo === 'HS09') {
          packingLength = 1560;
          packingWidth = 880;
          packingHeight = 650;
        } else if (prod.modelNo === 'HS10') {
          packingLength = 1580;
          packingWidth = 880;
          packingHeight = 660;
        } else if (prod.modelNo === 'HS11') {
          packingLength = 2250;
          packingWidth = 1100;
          packingHeight = 780;
        } else if (prod.modelNo === 'HS12') {
          packingLength = 1760;
          packingWidth = 840;
          packingHeight = 620;
        } else if (prod.modelNo === 'M9S12') {
          packingLength = 1880;
          packingWidth = 980;
          packingHeight = 720;
        } else if (prod.modelNo === 'M9s-013') {
          packingLength = 1750;
          packingWidth = 920;
          packingHeight = 680;
        } else if (prod.modelNo === 'TZ-5000') {
          packingLength = 1720;
          packingWidth = 950;
          packingHeight = 680;
        } else if (prod.modelNo === 'TZ-6000') {
          packingLength = 1750;
          packingWidth = 920;
          packingHeight = 680;
        } else if (prod.modelNo === 'ET-900') {
          packingLength = 620;
          packingWidth = 480;
          packingHeight = 440;
        } else if (prod.modelNo === 'ET-REFORMER-OAK') {
          packingLength = 2500;
          packingWidth = 780;
          packingHeight = 520;
        } else if (prod.modelNo === 'E7017') {
          packingLength = 2380;
          packingWidth = 1180;
          packingHeight = 680;
        } else if (prod.modelNo === 'BTW-6800') {
          packingLength = 1600;
          packingWidth = 880;
          packingHeight = 650;
        } else if (prod.modelNo === 'BTW-5000') {
          packingLength = 1680;
          packingWidth = 920;
          packingHeight = 680;
        } else {
          const maxDim = Math.max(prod.lengthMm || 1400, prod.heightMm || 1500);
          packingLength = Math.round(maxDim * 0.95 + 100);
          packingWidth = Math.round((prod.widthMm || 1200) * 0.65);
          packingHeight = 650;
        }
      }

      const packingCbm = (prod as any).packingCbm || parseFloat(((packingLength / 1000) * (packingWidth / 1000) * (packingHeight / 1000)).toFixed(3));

      const productValue: typeof products.$inferInsert = {
        productId: prod.productId,
        sku: prod.sku,
        title: prod.title,
        supplierId: sup.supplierId,
        supplierName: sup.supplierName,
        category1: prod.category1,
        category2: prod.category2,
        category3: prod.category3,
        priceMin: prod.priceMin,
        priceMax: prod.priceMax,
        currency: prod.currency,
        moq: prod.moq,
        modelNo: prod.modelNo,
        description: prod.description,
        descriptionHtml: `<p>${prod.description}</p>`,
        productUrl: prod.url,
        images: prod.images,
        productLine: prod.productLine,
        lengthMm: prod.lengthMm,
        widthMm: prod.widthMm,
        heightMm: prod.heightMm,
        netWeightKg: prod.netWeightKg,
        grossWeightKg: prod.grossWeightKg,
        packagingType: prod.packagingType,
        packingLengthMm: packingLength,
        packingWidthMm: packingWidth,
        packingHeightMm: packingHeight,
        packingCbm: packingCbm,
        certifications: prod.certifications,
        material: prod.material,
        specification: prod.specification,
        trademark: prod.trademark,
        transportPackage: prod.transportPackage,
        origin: prod.origin,
        hsCode: prod.hsCode,
        productionCapacity: prod.productionCapacity,
        rawJsonLd: {
          name: prod.title,
          brand: sup.supplierName,
          sku: prod.sku,
          model: prod.modelNo,
          offers: { price: prod.priceMax, priceCurrency: prod.currency },
        },
        rawAttributes: (prod.rawAttributes as unknown) as Record<string, string>,
        updatedAt: new Date(),
      };

      await db
        .insert(products)
        .values(productValue)
        .onConflictDoUpdate({
          target: products.productId,
          set: {
            title: prod.title,
            sku: prod.sku,
            productLine: prod.productLine,
            modelNo: prod.modelNo,
            lengthMm: prod.lengthMm,
            widthMm: prod.widthMm,
            heightMm: prod.heightMm,
            netWeightKg: prod.netWeightKg,
            grossWeightKg: prod.grossWeightKg,
            packagingType: prod.packagingType,
            packingLengthMm: packingLength,
            packingWidthMm: packingWidth,
            packingHeightMm: packingHeight,
            packingCbm: packingCbm,
            material: prod.material,
            specification: prod.specification,
            hsCode: prod.hsCode,
            description: prod.description,
            priceMin: prod.priceMin,
            priceMax: prod.priceMax,
            moq: prod.moq,
            updatedAt: new Date(),
          },
        });
    }
  }

  // Registra log de auditoria da carga de homologação
  const crawlLogValue: typeof crawlLogs.$inferInsert = {
    targetUrl: 'https://brtw-fitness.en.made-in-china.com/product-group/ToLazqByEHcs/2025-New-HS-Series-catalog-1.html',
    supplierId: 'sup_brtw_baodelong',
    productId: 'brtw_hs01_vertical_chest_press',
    status: 'completed',
    summary: 'Árvore de extração normalizada da 2025 New HS Series e 5 fábricas OEM',
    sourcesUsed: ['JSON-LD', 'Product Attributes DL/DD', 'Internal API getProductInfo', 'Internal API certificate', 'Internal API replyRate'],
    logDetails: {
      stepsLog: [
        { step: '1. Supplier Homepage Parsing', source: 'Supplier Homepage', status: 'success', details: 'Fábrica BRTW Baodelong homologada.' },
        { step: '2. Product Group (Linha)', source: 'product-group/2025-New-HS-Series', status: 'success', details: '12 SKUs normalizados na linha 2025 New HS Series.' },
        { step: '3. Technical Specs & Dimensions', source: 'dl.product-attrs-list & JSON-LD', status: 'success', details: 'Medidas L x W x H, Pesos PL/PB e Embalagem extraídos.' },
        { step: '4. Commercial Intelligence', source: 'Complementary APIs & Factory Profile', status: 'success', details: 'Preços FOB, MOQ 1 set, prazo 7-15 dias, pagamento T/T e L/C.' },
      ],
    },
  };

  await db.insert(crawlLogs).values(crawlLogValue);

  console.log('Árvore de extração normalizada e persistida com sucesso no PostgreSQL Cloud SQL!');
}

export async function ensureInitialSeedData() {
  try {
    const stats = await getDatabaseStats();
    // Se não tiver produtos ou se for a base inicial antiga com menos de 20 produtos, sincroniza a árvore completa
    if (stats.totalProducts < 20) {
      await seedAllTargetFactoriesAndLines();
    }
  } catch (error) {
    console.error('Error during initial seed check:', error);
  }
}
